### ISSUE TITLE
app.$storyblok is undefined even when loaded in editor

### ISSUE THREAD

**Issue by amp0024** [storyblok/nuxtwebsite#2]
I am looking to customize the storyblok init() function to include a customParent parameter, however everytime this function runs, app.$storyblok is undefined.

Any ideas as to why this would be?  My entire nuxt.config.js file is identical to this project...

**Comment by ademarCardoso** [comment]
Hi @amp0024 thanks to submit this issue, and sorry for the delay in answering you. Before, when you had not added the additional parameter, was the function performed normally? Post the fuction code please :)

**Comment by ademarCardoso** [comment]
Hello @amp0024 , I'm closing this issue, if you have any problems, please let us know :)
